# Generated by Django 5.1.1 on 2025-04-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
